apiVersion: apps/v1
kind: Deployment
metadata:
  name: jingyan-deployment
spec:
  replicas: 1  #number of pods at first
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: jingyanlou/detection_v3:latest #image used for the container
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"

